name: Trigger auto deployment for container-app-zqqzesxlf3jvy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-zqqzesxlf3jvy-AutoDeployTrigger-748e0c09-8296-4cd3-a213-4b30da16bb63.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZQQZESXLF3JVY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZQQZESXLF3JVY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZQQZESXLF3JVY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPZQQZESXLF3JVY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZQQZESXLF3JVY_REGISTRY_PASSWORD }}
          containerAppName: container-app-zqqzesxlf3jvy
          resourceGroup: nmappspacesragappa9ba
          imageToBuild: default/container-app-zqqzesxlf3jvy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


